apiVersion: v1
kind: Namespace
metadata:
  name: <color>
  labels:
    cbase: ss
---

apiVersion: v1
kind: Pod
metadata:
  namespace: <color>
  name: <color>app
  labels:
    app: <color>app
spec:
  containers:
  - image: cptdaks.azurecr.io/cpt/ss:1.0
    name: <color>app
    env:
      - name: PORTHTTP
        value: "8080"
      - name: SCOLOR
        value: "<color>"
    ports:
    - containerPort: 8080
      protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: <color>app
  namespace: <color>
spec:
  selector:
    app: <color>app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <color>app
  namespace: <color>
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/waf-policy-for-path: <wafrulerid>
spec:
  rules:
  - host: <color>.cptdaks.org
    http:
      paths:
      - path: /
        backend:
          service:
            name: <color>app
            port:
              number: 80
        pathType: Exact
